name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: "${GITHUB_WORKSPACE}/scripts/build.sh"
        shell: bash
      - name: Commit
        run: |
          if [ "$(git status --porcelain)" ]
          then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m 'automated build'
            git push
          fi
